package id.ac.ui.cs.advprog.beauthentication;

import com.fasterxml.jackson.databind.ObjectMapper;
import id.ac.ui.cs.advprog.beauthentication.repository.UserProfileRepository;
import id.ac.ui.cs.advprog.beauthentication.utils.JwtUtil;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import java.util.Map;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
class AuthControllerIntegrationTests {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private UserProfileRepository userProfileRepository;

        @Autowired
        private JwtUtil jwtUtil;

    @BeforeEach
    void setUp() {
        userProfileRepository.deleteAll();
    }

    @Test
    void shouldRegisterSuccessfullyWithoutReturningPassword() throws Exception {
        Map<String, String> registerRequest = Map.of(
                "username", "new_user",
                "email", "new_user@example.com",
                "password", "password123"
        );

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(registerRequest)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.message").value("Registrasi berhasil!"))
                .andExpect(jsonPath("$.data.username").value("new_user"))
                .andExpect(jsonPath("$.data.email").value("new_user@example.com"))
                .andExpect(jsonPath("$.data.role").value("TITIPER"))
                .andExpect(jsonPath("$.data.kycStatus").value("NOT_SUBMITTED"))
                .andExpect(jsonPath("$.data.password").doesNotExist());
    }

    @Test
    void shouldAutoGenerateUsernameWhenNotProvided() throws Exception {
        Map<String, String> registerRequest = Map.of(
                "email", "auto.username@example.com",
                "password", "password123"
        );

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(registerRequest)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.username").isString())
                .andExpect(jsonPath("$.data.username").isNotEmpty())
                .andExpect(jsonPath("$.data.role").value("TITIPER"))
                .andExpect(jsonPath("$.data.kycStatus").value("NOT_SUBMITTED"));
    }

    @Test
    void shouldAutoGenerateUsernameWhenBlankUsernameProvided() throws Exception {
        Map<String, String> registerRequest = Map.of(
                "username", "   ",
                "email", "blank.username@example.com",
                "password", "password123"
        );

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(registerRequest)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.username").isString())
                .andExpect(jsonPath("$.data.username").isNotEmpty());
    }

    @Test
    void shouldNormalizeEmailOnRegister() throws Exception {
        Map<String, String> registerRequest = Map.of(
                "email", "Mixed.Case@Example.COM",
                "password", "password123"
        );

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(registerRequest)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.email").value("mixed.case@example.com"));
    }

    @Test
    void shouldAutoGenerateDifferentUsernameWhenBaseIsAlreadyUsed() throws Exception {
        Map<String, String> firstRegister = Map.of(
                "email", "same.local@gmail.com",
                "password", "password123"
        );

        Map<String, String> secondRegister = Map.of(
                "email", "same.local@yahoo.com",
                "password", "password123"
        );

        MvcResult firstResult = mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(firstRegister)))
                .andExpect(status().isOk())
                .andReturn();

        MvcResult secondResult = mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(secondRegister)))
                .andExpect(status().isOk())
                .andReturn();

        String firstUsername = objectMapper.readTree(firstResult.getResponse().getContentAsString())
                .path("data").path("username").asText();
        String secondUsername = objectMapper.readTree(secondResult.getResponse().getContentAsString())
                .path("data").path("username").asText();

        org.junit.jupiter.api.Assertions.assertNotEquals(firstUsername, secondUsername);
    }

    @Test
    void shouldRejectDuplicateRegisterByUsername() throws Exception {
        Map<String, String> firstRegister = Map.of(
                "username", "duplicate_user",
                "email", "dup1@example.com",
                "password", "password123"
        );

        Map<String, String> secondRegister = Map.of(
                "username", "duplicate_user",
                "email", "dup2@example.com",
                "password", "password123"
        );

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(firstRegister)))
                .andExpect(status().isOk());

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(secondRegister)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("Username atau Email sudah terdaftar!"));
    }

    @Test
    void shouldRejectDuplicateRegisterByEmail() throws Exception {
        Map<String, String> firstRegister = Map.of(
                "username", "first_user",
                "email", "same_email@example.com",
                "password", "password123"
        );

        Map<String, String> secondRegister = Map.of(
                "username", "second_user",
                "email", "same_email@example.com",
                "password", "password123"
        );

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(firstRegister)))
                .andExpect(status().isOk());

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(secondRegister)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("Username atau Email sudah terdaftar!"));
    }

    @Test
    void shouldRejectDuplicateRegisterByEmailIgnoringCase() throws Exception {
        Map<String, String> firstRegister = Map.of(
                "username", "case_user_one",
                "email", "CaseEmail@Example.com",
                "password", "password123"
        );

        Map<String, String> secondRegister = Map.of(
                "username", "case_user_two",
                "email", "caseemail@example.com",
                "password", "password123"
        );

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(firstRegister)))
                .andExpect(status().isOk());

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(secondRegister)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("Username atau Email sudah terdaftar!"));
    }

    @Test
    void shouldRejectRegisterWithInvalidEmailFormat() throws Exception {
        Map<String, String> registerRequest = Map.of(
                "email", "invalid-email-format",
                "password", "password123"
        );

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(registerRequest)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("Format email tidak valid!"));
    }

    @Test
    void shouldLoginSuccessfullyWithEmailAndPassword() throws Exception {
        Map<String, String> registerRequest = Map.of(
                "username", "login_user",
                "email", "login_user@example.com",
                "password", "password123"
        );

        Map<String, String> loginRequest = Map.of(
                "email", "LOGIN_USER@EXAMPLE.COM",
                "password", "password123"
        );

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(registerRequest)))
                .andExpect(status().isOk());

        MvcResult loginResult = mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(loginRequest)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.message").value("Login berhasil!"))
                .andExpect(jsonPath("$.data.token").isString())
                .andReturn();

        String token = objectMapper.readTree(loginResult.getResponse().getContentAsString())
                .path("data").path("token").asText();

        Assertions.assertEquals("TITIPER", jwtUtil.extractRole(token));
        Assertions.assertEquals("login_user@example.com", jwtUtil.extractUsername(token));
    }

    @Test
    void shouldRejectLoginWithWrongPasswordAsUnauthorized() throws Exception {
        Map<String, String> registerRequest = Map.of(
                "username", "wrong_pass_user",
                "email", "wrong_pass@example.com",
                "password", "password123"
        );

        Map<String, String> loginRequest = Map.of(
                "email", "wrong_pass@example.com",
                "password", "not_the_right_password"
        );

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(registerRequest)))
                .andExpect(status().isOk());

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(loginRequest)))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.message").value("Password salah!"));
    }

    @Test
    void shouldRejectLoginWhenEmailNotFoundAsUnauthorized() throws Exception {
        Map<String, String> loginRequest = Map.of(
                "email", "unknown_user@example.com",
                "password", "password123"
        );

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(loginRequest)))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.message").value("Email tidak ditemukan!"));
    }

    @Test
    void shouldRejectLoginWithInvalidEmailFormatAsBadRequest() throws Exception {
        Map<String, String> loginRequest = Map.of(
                "email", "invalid-email-format",
                "password", "password123"
        );

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(loginRequest)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("Format email tidak valid!"));
    }

    @Test
    void shouldRejectRegisterWithBlankRequiredFields() throws Exception {
        Map<String, String> registerRequest = Map.of(
                "username", "   ",
                "email", "",
                "password", ""
        );

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(registerRequest)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("Email dan password wajib diisi!"));
    }

    @Test
    void shouldRejectRegisterWithShortPassword() throws Exception {
        Map<String, String> registerRequest = Map.of(
                "username", "short_pass_user",
                "email", "short_pass@example.com",
                "password", "short1"
        );

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(registerRequest)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("Password minimal 8 karakter!"));
    }

    @Test
    void shouldRejectLoginWithBlankRequiredFields() throws Exception {
        Map<String, String> loginRequest = Map.of(
                "email", " ",
                "password", ""
        );

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(loginRequest)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("Email dan password wajib diisi!"));
    }

    @Test
    void shouldAccessProtectedEndpointUsingTokenFromLogin() throws Exception {
        Map<String, String> registerRequest = Map.of(
                "username", "e2e_user",
                "email", "e2e_user@example.com",
                "password", "password123"
        );

        Map<String, String> loginRequest = Map.of(
                "email", "e2e_user@example.com",
                "password", "password123"
        );

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(registerRequest)))
                .andExpect(status().isOk());

        MvcResult loginResult = mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(loginRequest)))
                .andExpect(status().isOk())
                .andReturn();

        String responseBody = loginResult.getResponse().getContentAsString();
        String token = objectMapper.readTree(responseBody).path("data").path("token").asText();

        mockMvc.perform(get("/api/profile/all")
                        .header("Authorization", "Bearer " + token))
                .andExpect(status().isOk());
    }

    @Test
    void shouldRejectLoginWhenUserIsBanned() throws Exception {
        Map<String, String> registerRequest = Map.of(
                "username", "banned_login_user",
                "email", "banned_login_user@example.com",
                "password", "password123"
        );

        mockMvc.perform(post("/api/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(registerRequest)))
                .andExpect(status().isOk());

        userProfileRepository.findByEmail("banned_login_user@example.com").ifPresent(user -> {
            user.setAccountStatus("BANNED");
            userProfileRepository.save(user);
        });

        Map<String, String> loginRequest = Map.of(
                "email", "banned_login_user@example.com",
                "password", "password123"
        );

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(loginRequest)))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.message").value("Akun Anda telah di-ban!"));
    }
}
